"""add embedding_status to knowledge_documents

Revision ID: 55e16bed1497
Revises: 007
Create Date: 2026-06-21 23:56:26.355896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e16bed1497'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aer_generated_question_id'), table_name='adaptive_exam_responses')
    op.create_index(op.f('ix_adaptive_exam_responses_generated_question_id'), 'adaptive_exam_responses', ['generated_question_id'], unique=False)
    op.drop_index(op.f('ix_evidence_chunk_id'), table_name='generated_question_evidence')
    op.drop_index(op.f('ix_evidence_generated_question_id'), table_name='generated_question_evidence')
    op.create_index(op.f('ix_generated_question_evidence_chunk_id'), 'generated_question_evidence', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_generated_question_evidence_generated_question_id'), 'generated_question_evidence', ['generated_question_id'], unique=False)
    op.drop_index(op.f('ix_reviews_generated_question_id'), table_name='generated_question_reviews')
    op.create_index(op.f('ix_generated_question_reviews_generated_question_id'), 'generated_question_reviews', ['generated_question_id'], unique=False)
    op.alter_column('generated_questions', 'review_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('knowledge_documents', sa.Column('embedding_status', sa.String(length=20), server_default='pending', nullable=False))
    op.alter_column('student_topic_progress', 'current_streak',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_topic_progress', 'questions_asked',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('student_topic_progress', 'generated_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_stp_exam_id'), table_name='student_topic_progress')
    op.drop_index(op.f('ix_stp_student_id'), table_name='student_topic_progress')
    op.drop_index(op.f('ix_stp_topic_id'), table_name='student_topic_progress')
    op.create_index(op.f('ix_student_topic_progress_exam_id'), 'student_topic_progress', ['exam_id'], unique=False)
    op.create_index(op.f('ix_student_topic_progress_student_id'), 'student_topic_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_topic_progress_topic_id'), 'student_topic_progress', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_topic_progress_topic_id'), table_name='student_topic_progress')
    op.drop_index(op.f('ix_student_topic_progress_student_id'), table_name='student_topic_progress')
    op.drop_index(op.f('ix_student_topic_progress_exam_id'), table_name='student_topic_progress')
    op.create_index(op.f('ix_stp_topic_id'), 'student_topic_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_stp_student_id'), 'student_topic_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_stp_exam_id'), 'student_topic_progress', ['exam_id'], unique=False)
    op.alter_column('student_topic_progress', 'generated_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_topic_progress', 'questions_asked',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('student_topic_progress', 'current_streak',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('knowledge_documents', 'embedding_status')
    op.alter_column('generated_questions', 'review_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_generated_question_reviews_generated_question_id'), table_name='generated_question_reviews')
    op.create_index(op.f('ix_reviews_generated_question_id'), 'generated_question_reviews', ['generated_question_id'], unique=False)
    op.drop_index(op.f('ix_generated_question_evidence_generated_question_id'), table_name='generated_question_evidence')
    op.drop_index(op.f('ix_generated_question_evidence_chunk_id'), table_name='generated_question_evidence')
    op.create_index(op.f('ix_evidence_generated_question_id'), 'generated_question_evidence', ['generated_question_id'], unique=False)
    op.create_index(op.f('ix_evidence_chunk_id'), 'generated_question_evidence', ['chunk_id'], unique=False)
    op.drop_index(op.f('ix_adaptive_exam_responses_generated_question_id'), table_name='adaptive_exam_responses')
    op.create_index(op.f('ix_aer_generated_question_id'), 'adaptive_exam_responses', ['generated_question_id'], unique=False)
    # ### end Alembic commands ###